type: YUGABYTE
createdb: drop database if exists cyugabyte; create database cyugabyte with colocated=true;
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://172.156.42.143:5433/cyugabyte?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
username: yugabyte
password: Stiwary@benchmarking16
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
works:
    work:
        time: 5
        active_terminals: 1
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
    properties:
        setAutoCommit : true
        create :
            - drop table if exists demo;
            - drop table if exists demo_indexes_1;
            - drop table if exists demo_indexes_2;
            - drop table if exists demo_indexes_3;
            - drop table if exists demo_indexes_5;
            - drop table if exists demo_indexes_10;

            - drop index if exists demo_indexes_1_idx1;

            - drop index if exists demo_indexes_2_idx1;
            - drop index if exists demo_indexes_2_idx2;

            - drop index if exists demo_indexes_3_idx1;
            - drop index if exists demo_indexes_3_idx2;
            - drop index if exists demo_indexes_3_idx3;

            - drop index if exists demo_indexes_5_idx1;
            - drop index if exists demo_indexes_5_idx2;
            - drop index if exists demo_indexes_5_idx3;
            - drop index if exists demo_indexes_5_idx4;
            - drop index if exists demo_indexes_5_idx5;

            - drop index if exists demo_indexes_10_idx1;
            - drop index if exists demo_indexes_10_idx2;
            - drop index if exists demo_indexes_10_idx3;
            - drop index if exists demo_indexes_10_idx4;
            - drop index if exists demo_indexes_10_idx5;
            - drop index if exists demo_indexes_10_idx6;
            - drop index if exists demo_indexes_10_idx7;
            - drop index if exists demo_indexes_10_idx8;
            - drop index if exists demo_indexes_10_idx9;
            - drop index if exists demo_indexes_10_idx10;

            - create table demo (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);
            - create table demo_indexes_1 (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);
            - create table demo_indexes_2 (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);
            - create table demo_indexes_3 (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);
            - create table demo_indexes_5 (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);
            - create table demo_indexes_10 (id int not null primary key, col1 int not null, col2 int, col3 int, col4 int, col5 int, col6 int, col7 int, col8 int, col9 int, col10 int);

            - create unique index demo_indexes_1_idx1 on demo(col1);

            - create unique index demo_indexes_2_idx1 on demo(col1);
            - create unique index demo_indexes_2_idx2 on demo(col2);

            - create unique index demo_indexes_3_idx1 on demo(col1);
            - create unique index demo_indexes_3_idx2 on demo(col2);
            - create unique index demo_indexes_3_idx3 on demo(col3);

            - create unique index demo_indexes_5_idx1 on demo(col1);
            - create unique index demo_indexes_5_idx2 on demo(col2);
            - create unique index demo_indexes_5_idx3 on demo(col3);
            - create unique index demo_indexes_5_idx4 on demo(col4);
            - create unique index demo_indexes_5_idx5 on demo(col5);

            - create unique index demo_indexes_10_idx1 on demo(col1);
            - create unique index demo_indexes_10_idx2 on demo(col2);
            - create unique index demo_indexes_10_idx3 on demo(col3);
            - create unique index demo_indexes_10_idx4 on demo(col4);
            - create unique index demo_indexes_10_idx5 on demo(col5);
            - create unique index demo_indexes_10_idx6 on demo(col6);
            - create unique index demo_indexes_10_idx7 on demo(col7);
            - create unique index demo_indexes_10_idx8 on demo(col8);
            - create unique index demo_indexes_10_idx9 on demo(col9);
            - create unique index demo_indexes_10_idx10 on demo(col10);
