type: YUGABYTE
driver: com.yugabyte.Driver
url: jdbc:yugabytedb://10.150.0.170:5433/cyugabyte?sslmode=disable&ApplicationName=featurebench&reWriteBatchedInserts=true&load-balance=false
username: yugabyte
password: Yugabyte@123
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 1
terminals: 1
works:
    work:
        time: 5
        active_terminals: 1
        rate: 1000
        warmup: 0
microbenchmark:
    class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBMicroBenchmarkUpdatesBatchedIndexes2ExpTxn
    properties:
        setAutoCommit : true
        create :
            - DROP PROCEDURE if exists insert_demo;
            - CREATE PROCEDURE insert_demo(_numRows int)
              LANGUAGE plpgsql
              AS $$
              DECLARE
              BEGIN
              insert into demo_indexes_2 (id, col1, col2, col3, col4, col5, col6, col7, col8, col9, col10) select n, n, n, n, n, n, n, n, n, n, n from generate_series(1,_numRows) n;
              END;
              $$;
