type: YUGABYTE
driver: com.yugabyte.Driver
# The DB to connect will be yb_colocated and it must be created beforehand.
url: jdbc:yugabytedb://172.156.31.223:5433/yb_colocated?sslmode=require&ApplicationName=featurebench&reWriteBatchedInserts=true
# Commented because we need the DB and Tables to exist so that we can deterministicly know whether we're hitting the tablet leader or not.
# createdb: create database yb_colocated with colocated=true
username: yugabyte
password: Stiwary@benchmarking16
batchsize: 128
isolation: TRANSACTION_REPEATABLE_READ
loaderthreads: 4
terminals: 1
works:
  work:
    time_secs: 120
    active_terminals: 1
    rate: unlimited
    warmup: 10
microbenchmark:
  class: com.oltpbenchmark.benchmarks.featurebench.customworkload.YBDefaultMicroBenchmark
  properties:
    setAutoCommit: true
    # Just for reference as the DDL commands should already be run for determinism. Ensure to run with --create = false.
    create:
      - drop table if exists index_test_1;
      - drop table if exists index_test_2;
      - create table index_test_1 (id int primary key, col_int_1 int, col_int_2 int, col_int_3 int, col_int_4 int, col_int_5 int, col_int_6 int, col_int_7 int, col_int_8 int, col_int_9 int, col_int_10 int, col_varchar_1 varchar(20), col_varchar_2 varchar(20), col_varchar_3 varchar(20), col_date text, col_boolean boolean)
      - create table index_test_2 (id int primary key, col_int_1 int, col_int_2 int, col_int_3 int, col_int_4 int, col_int_5 int, col_int_6 int, col_int_7 int, col_int_8 int, col_int_9 int, col_int_10 int, col_varchar_1 varchar(20), col_varchar_2 varchar(20), col_varchar_3 varchar(20), col_date text, col_boolean boolean)
      - create index index_test_2_idx1 on index_test_2(col_int_1);
    loadRules:
      - table: index_test_
        count: 2
        rows: 1000
        columns:
          - name: id
            util: PrimaryIntGen
            params:
              - 1
              - 1000
          - name: col_int_
            count: 10
            util: RandomNumber
            params:
              - 1
              - 1000000
          - name: col_varchar_
            count: 3
            util: RandomAString
            params:
              - 20
              - 20
          - name: col_date
            util: RandomAString
            params:
              - 20
              - 20
          - name: col_boolean
            util: RandomBoolean
    executeRules:
      - workload: no_index
        run:
          - name: Insert_without_index_test
            weight: 100
            queries:
              - query: INSERT INTO index_test_1 (id, col_int_1, col_int_2, col_int_3, col_int_4, col_int_5, col_int_6, col_int_7, col_int_8, col_int_9, col_int_10, col_varchar_1, col_varchar_2, col_varchar_3, col_date, col_boolean) values (?, ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                bindings:
                  - util: PrimaryIntGen
                    params:
                      - 1001
                      - 2000
                  - util: RandomNumber
                    count: 10
                    params:
                      - 1
                      - 1000000
                  - util: RandomAString
                    count: 3
                    params:
                      - 20
                      - 20
                  - util: RandomAString
                    params:
                      - 20
                      - 20
                  - util: RandomBoolean
      - workload: 1_index_test
        run:
          - name: Insert_with_1_index_test
            weight: 100
            queries:
              - query: INSERT INTO index_test_2 (id, col_int_1, col_int_2, col_int_3, col_int_4, col_int_5, col_int_6, col_int_7, col_int_8, col_int_9, col_int_10, col_varchar_1, col_varchar_2, col_varchar_3, col_date, col_boolean) values (?, ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                bindings:
                  - util: PrimaryIntGen
                    params:
                      - 2001
                      - 3000
                  - util: RandomNumber
                    count: 10
                    params:
                      - 1
                      - 1000000
                  - util: RandomAString
                    count: 3
                    params:
                      - 20
                      - 20
                  - util: RandomAString
                    params:
                      - 20
                      - 20
                  - util: RandomBoolean